spring.application.name=ai-career-assistant

# DATABASE CONFIG
spring.datasource.url=jdbc:mysql://localhost:3306/ai_career_assistant
spring.datasource.username=root
spring.datasource.password=root123

# JPA CONFIG
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# SERVER
server.port=8080